# **1 - TRAINING DATA**

In [10]:
# features (1 sim, 0 não)
# --------------------------------------------------
# Animal   | Pelo longo? | Perna curta? | Faz AuAu?|
# Porco    |       0     |       1      |     0    |
# Porco    |       0     |       1      |     1    |
# Porco    |       1     |       1      |     0    |
# Cachorro |       0     |       1      |     1    |
# Cachorro |       1     |       0      |     1    |
# Cachorro |       1     |       1      |     1    |

pig1 = [0, 1, 0]
pig2 = [0, 1, 1]
pig3 = [1, 1, 0]

dog1 = [0, 1, 1]
dog2 = [1, 0, 1]
dog3 = [1, 1, 1]
# f(x) = y ( função de train_x tem que ser igual a train_y)
# 1 => porco, 0 => cachorro
train_x = [pig1, pig2, pig3, dog1, dog2, dog3]
# Classes
train_y = [1,1,1,0,0,0]

# **2 - Importing SKLEARN**

In [12]:
from sklearn.svm import LinearSVC

# Creating the Estimator
model = LinearSVC()
# Training the Estimator
model.fit(train_x, train_y)

LinearSVC()

# **3 - TEST DATA**

In [15]:
mysterious_animal = [1, 1, 1]
model.predict([mysterious_animal]) # result = 0 is dog

array([0])

In [20]:
mysterious1 = [1, 1, 1] # dog
mysterious2 = [1, 1, 0] # pig
mysterious3 = [0, 1, 1] # pig

# Predictions
test_x = [mysterious1, mysterious2, mysterious3]
test_y = [0, 1, 1]

# Trying to predict with the model
model.predict(test_x) # [cachorro, porco, cachorro] -> errou o ultimo

array([0, 1, 0])

# **Taxa de acerto**

In [22]:
predictions = model.predict(test_x)
predictions

array([0, 1, 0])

In [23]:
predictions == test_y

array([ True,  True, False])

In [27]:
# We can sum the numpy array returned 
correct = (predictions == test_y).sum()
print(correct)
total = len(test_x)
print(total)
hit_rate = correct/total
print('Taxa de acerto: ', round(hit_rate * 100,2),'%')

2
3
Taxa de acerto:  66.67 %


In [26]:
from sklearn.metrics import accuracy_score
hit_rate = accuracy_score(test_y, predictions)
print('Taxa de acerto: ', round(hit_rate *100,2),'%' )

Taxa de acerto:  66.67 %
